# -*- coding: utf-8 -*-
"""NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0yfHSjvyXpBHhI02TMbqSOaIZy_G3s9
"""

import  torch
import torch.nn as nn

model=nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

